server:
  port: 8099
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.75.243.232:3306/annotator?useUnicode=true&characterEncoding=utf8
    username: root
    password: bobo201308@
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl-auto: create
    show-sql: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#spring.jpa.database-platform=

